# Generated by Django 4.2.4 on 2023-08-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email_us', models.CharField(blank=True, max_length=25, null=True)),
                ('subtitle', models.TextField(blank=True, max_length=200, null=True)),
                ('phones', models.TextField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
                ('fb_link', models.URLField(blank=True, null=True)),
                ('insta_link', models.URLField(blank=True, null=True)),
                ('x_link', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
