# Generated by Django 4.2.4 on 2023-08-28 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_desc_products_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='products',
            name='title',
        ),
    ]
