# Generated by Django 4.2.4 on 2023-08-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_products_desc_remove_products_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
